name: Playwright VRT

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  actions: write

jobs:
  vrt:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      SNAPSHOT_ARTIFACT_NAME: snapshots-${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: latest

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps chromium

    - name: Download snapshots
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        artifact_id=$(gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "/repos/${{ github.repository }}/actions/artifacts?name=${{ env.SNAPSHOT_ARTIFACT_NAME }}" \
        | jq -r '.artifacts[0].id')

        if [[ -z "$artifact_id" || "$artifact_id" == "null" ]]; then
          echo "::warning::Artifact not found. Skipping further steps."
          exit 0
        fi

        gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "/repos/${{ github.repository }}/actions/artifacts/${artifact_id}/zip" >> snapshot.zip
        unzip snapshot.zip -d ./snapshots

        rm -rf snapshot.zip

    - name: Run Playwright tests
      run: pnpm exec playwright test ./tests/vrt.spec.ts --update-snapshots

    - name: Upload snapshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.SNAPSHOT_ARTIFACT_NAME }}
        path: ./snapshots

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report-vrt
        path: playwright-report/
        retention-days: 30
